### ISSUE TITLE
error on make....

### ISSUE THREAD

**Issue by hs6666** [FileGo/octopusenergy-influxdb#5]
Hi,

Sorry new to programming :)

downloaded zip file to my raspberry pi (running influxdb), extracted and updated the config.yml file 

then ran "make" in the folder and got the following output...

go build -o octopusenergy-influxdb .
make: go: Command not found
make: *** [Makefile:2: build] Error 127

Any ideas please?

thanks

Harry

**Comment by FileGo** [comment]
You need to install Go on your Raspberry Pi: https://go.dev/doc/install

**Comment by hs6666** [comment]
thanks, perfect, data successfully imported :)

Now to create a dashboard with the data, I'm running grafana on the same pi... a newbie to grafana too!

thanks again
